### ISSUE TITLE
Why the Microsoft Reciprocal License?

### ISSUE THREAD

**Issue by JonMcPherson** [porrey/Solar-Calculator#5]
It is incompatible with the GNU GPL and also requires all files that contains code from the program and all modified or extended versions of the program to be open sourced as well...

Could you use a less restrictive and more compatible license?

**Comment by porrey** [comment]
I have no issue changing it. I changed it once a got some backlash and had to restore it. I can change it if others that are using agree.

**Comment by JonMcPherson** [comment]
I'm curious why people were upset about the previous GNU GPL license.

**Comment by JonMcPherson** [comment]
A license without copyleft would be great.
I'd like to keep what I'm working on closed source especially considering this library would only be used for a very minor feature in an insignificant way.

**Comment by porrey** [comment]
Version 3.0.0 is now GNU General Public License v3.0. All versions prior remain on previous license.

**Comment by JonMcPherson** [comment]
ahh GNU GPL is still copyleft and requires distributed works to release source code (with build instructions) also licensed under GNU GPL.
So for example, this library could not be used in commercial mobile apps that should be"closed source".

**Comment by porrey** [comment]
I can change it to LGPL if this works, but not comfortable with other licenses for this library.


On Jan 24, 2020, at 10:44 PM, Jon McPherson <notifications@github.com<mailto:notifications@github.com>> wrote:


ahh GNU GPL is still copyleft and requires distributed works to release source code (with build instructions) also licensed under GNU GPL.
So for example, this library could not be used in commercial mobile apps that should be"closed source".
