### ISSUE TITLE
SolarTimes DST regression in 3.0.4

### ISSUE THREAD

**Issue by mfeingol** [porrey/Solar-Calculator#7]
Hello. Version 3.0.4 of the library has a regression calculating sunset times over DST.

For example, the sunset time for `47.606165, -122.342435` on 2017-11-5 is wrong. It should be 16:46:44 local time according to https://sunrise-sunset.org/us/seattle-wa/2017/11 but `SolarTimes` returns 17:46:44, which would be correct if it weren't for DST.

Please let me know if you have trouble reproducing this. It works in 3.0.3.

Thanks.

**Comment by porrey** [comment]
Last change was reverted until I can do further research on some specialized cases that are failing tests. I am looking to add some additional tests as well.
