### ISSUE TITLE
Add properties for Dawn and Dusk

### ISSUE THREAD

**Issue by rbdavison** [porrey/Solar-Calculator#8]
G'Day,

I like your library but think it could be better if some more properties were calculated.
Specifically I'm thinking of:
- Astronomical Dawn
- Nautical Dawn
- Civil Dawn
- Civil Dusk
- Nautical Dusk
- Astronomical Dusk

I'm happy to help our am looking through your code.
But if you know how to fix it before I can create a pull request that would make my life easier.

**Comment by porrey** [comment]
I would have to do some research before tackling these.

**Comment by rbdavison** [comment]
No worries on the research. I expect you'll want to make the necessary adjustments the test spreadsheet and CSV file.
The code is in the PR https://github.com/porrey/Solar-Calculator/pull/9

**Comment by rbdavison** [comment]
G'Day Daniel,

I was wondering if you'd had a chance to look at this pull request.
Is there anything you need to aid in the integration.

Cheers,

**Comment by porrey** [comment]
> G'Day Daniel,
> 
> I was wondering if you'd had a chance to look at this pull request.
> Is there anything you need to aid in the integration.
> 
> Cheers,

It appears one of the new tests is failing in regards to Dusk/Dawn calculations.

**Comment by rbdavison** [comment]
Yeah I don't know why the unit test is failing. It works locally.
I can't seem to get any visibility into the build system so was hoping that it would be something you could provide some details on.
